# Generated by Django 4.2.3 on 2023-07-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.money'),
        ),
    ]
