# Generated by Django 4.2.3 on 2023-07-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='card',
            new_name='cardg',
        ),
    ]
