# Generated by Django 4.2.3 on 2023-07-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_remove_money_card_money_cardh'),
        ('users', '0003_rename_card_user_cardg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cardg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cash.money'),
        ),
    ]
