# Generated by Django 4.2.3 on 2023-07-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=8)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
