# Generated by Django 4.2.3 on 2023-07-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='card',
        ),
        migrations.AddField(
            model_name='money',
            name='cardh',
            field=models.CharField(blank=True, default=True, max_length=8, null=True),
        ),
    ]
